import { Container } from "react-bootstrap";
import "../css/Service.css";
import Layout from "../components/Layout";

function Service() {
  return (
    <Layout>
      <Container>
        <div>
          <h1 className="title-service">Terms Of Service</h1>
        </div>
        <div>
          <p className="p-service">
            Effective date: August 4, 2023 <br /> Anki Education, LLC. (“us”,
            “we”, or “our”) operates the{" "}
            <a href="https://anki.edu.vn/">https://anki.edu.vn</a> website and
            the Anki Education mobile application (the “Service”). <br /> This
            page informs you of our policies regarding the collection, use, and
            disclosure of personal data when you use our Service and the choices
            you have associated with that data. <br /> We use your data to
            provide and improve the Service. By using the Service, you agree to
            the collection and use of information in accordance with this
            policy. Unless otherwise defined <br /> in this Privacy Policy,
            terms used in this Privacy Policy have the same meanings as in our
            Terms and Conditions.
          </p>
        </div>
        <div>
          <h3 className="def mt-2">Definitions</h3>
          <h5 className="ser-h5">Service</h5>
          <p className="p-ser">
            Service means the{" "}
            <a href="https://anki.edu.vn/">https://anki.edu.vn</a> website and
            the Anki Education mobile application operated by Anki Education,
            LLC.
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Personal Data</h5>
          <p className="p-ser">
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Usage Data</h5>
          <p className="p-ser">
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Cookies</h5>
          <p className="p-ser">
            Cookies are small pieces of data stored on your device (computer or
            mobile device).
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Data Controller</h5>
          <p className="p-ser">
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed. For the purpose of this Privacy Policy, we are
            a Data Controller of your Personal Data.
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Data Processors (or Service Providers)</h5>
          <p className="p-ser">
            Data Processor (or Service Provider) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
        </div>
        <div>
          <h5 className="ser-h5">Data Subject (or User)</h5>
          <p className="p-ser">
            Data Subject is any living individual who is using our Service and
            is the subject of Personal Data.
          </p>
        </div>
        <div>
          <h3 className="def mt-2">Information Collection and Use</h3>
          <p className="p-ser">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>
        <div>
          <h3 className="def mt-2">Types of Data Collected</h3>
          <h5 className="ser-h5">Personal Data</h5>
          <p className="p-ser2">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally <br /> identifiable
            information may include, but is not limited to: <br /> First name
            and last name <br /> Email address <br /> Cookies and Usage Data{" "}
            <br /> We may use your Personal Data to contact you with
            newsletters, marketing or promotional materials and other
            information that may be of interest to you. <br /> You may opt out
            of receiving any, or all, of these communications from us by
            following the unsubscribe link or instructions provided in any email
            we send or by contacting us.
          </p>
        </div>
      </Container>
    </Layout>
  );
}
export default Service;
